# Generated by Django 4.1 on 2023-02-08 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_prodcut_reviewrating_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='raiting',
            new_name='rating',
        ),
    ]
