# Generated by Django 3.1 on 2023-02-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20230213_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('talla', 'talla'), ('color', 'color')], max_length=100),
        ),
    ]
