# Generated by Django 3.1 on 2023-02-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('talla', 'talla')], max_length=100),
        ),
    ]
