# Generated by Django 4.1 on 2023-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelado'), ('Accepted', 'Aceptado'), ('Completed', 'Completado'), ('New', 'Nuevo')], default='New', max_length=50),
        ),
    ]
