# Generated by Django 4.1 on 2023-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado'), ('Accepted', 'Aceptado')], default='New', max_length=50),
        ),
    ]
