# Generated by Django 3.1 on 2023-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20230213_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Aceptado'), ('Completed', 'Completado'), ('New', 'Nuevo'), ('Cancelled', 'Cancelado')], default='New', max_length=50),
        ),
    ]
