# Generated by Django 3.1 on 2023-02-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20230214_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Cancelled', 'Cancelado'), ('Completed', 'Completado'), ('Accepted', 'Aceptado')], default='New', max_length=50),
        ),
    ]
