# Generated by Django 3.1 on 2023-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20230218_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completado'), ('Accepted', 'Aceptado'), ('New', 'Nuevo'), ('Cancelled', 'Cancelado')], default='New', max_length=50),
        ),
    ]
